use super::*;

pub(in super::super) const SLOT_HASHES: &str = "SysvarS1otHashes111111111111111111111111111";

pub(in super::super) const ALPENGLOW: &str = "a1penGLz8Vm2QHYB3JPefBiU4BY3Z6JkW2k3Scw5GWP";

pub(in super::super) const POLICY: &str = "reserved-exempt-explicit-override-baseline/v1";

pub(in super::super) const PARENT_SYSVARS: [&str; 4] = [
    "SysvarS1otHistory11111111111111111111111111",
    "SysvarFees111111111111111111111111111111111",
    "SysvarRecentB1ockHashes11111111111111111111",
    "SysvarRewards111111111111111111111111111111",
];

// Reviewed prototype source identities, not evidence generated by this port.
pub(in super::super) const BANK_SOURCES: [(&str, &str); 6] = [
    (
        "litesvm-v0.7.1-agave-2.3.9",
        "47647df756f5dd0b3c739cecaa71bcf754af6be8",
    ),
    (
        "litesvm-v0.8.2-agave-3.0.10",
        "96c3a8519a3bac8c7e7dd49b6d6aefcfeba09d90",
    ),
    (
        "litesvm-v0.12.0-agave-3.1.11",
        "81d1f5fb0c75203329468250df3769393ab1479b",
    ),
    (
        "litesvm-v0.13.1-agave-4.0.0",
        "2a165e7a90af75c76426d1e031ed0284211d5d1e",
    ),
    (
        "litesvm-v0.14.0-pr402-agave-4.1.2",
        "182084b82aae88b1b0731540f63bf7416f27773a",
    ),
    (
        "litesvm-v0.16.0-agave-4.2.1",
        "c4b48df969a9e4f121e14a389bd7bec34c752507",
    ),
];

pub struct OverrideSysvarContext<'a> {
    pub parent_slot: u64,
    pub target_slot: u64,
    pub executor_source_id: &'a str,
    /// Explicit captured execution-feature array; missing/malformed is not empty.
    pub active_execution_feature_ids: &'a Value,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct OverrideSysvarBaselines {
    pub accounts: Vec<Value>,
    pub bindings: Vec<Value>,
    pub generic_sysvars: Vec<Value>,
}

pub(in super::super) fn bank_source(source: &str) -> Option<&'static str> {
    BANK_SOURCES
        .iter()
        .find(|(id, _)| *id == source)
        .map(|(_, commit)| *commit)
}

pub(in super::super) fn valid_boundary(c: &OverrideSysvarContext<'_>) -> bool {
    c.target_slot <= 9_007_199_254_740_991 && c.parent_slot < c.target_slot
}

pub(in super::super) fn features(value: &Value) -> Result<()> {
    let reject = |message: &str| unsupported("UNSUPPORTED_RUNTIME_PROFILE", "PREFLIGHT", message);
    let values = value.as_array().ok_or_else(|| {
        reject("override sysvar phase proof requires bound active execution features")
    })?;
    if values.iter().any(|v| !v.is_string()) {
        return Err(reject(
            "override sysvar phase proof requires bound active execution features",
        ));
    }
    if values.iter().any(|v| v == ALPENGLOW) {
        return Err(reject("Alpenglow override sysvar initialization/freeze phase is outside the reviewed Tower proof"));
    }
    Ok(())
}

pub(in super::super) fn assert_image(account: &Value, slot: u64) -> Result<()> {
    let valid_lamports = account["lamports"].as_str().is_some_and(|text| {
        text.parse::<u64>()
            .is_ok_and(|n| n > 0 && n.to_string() == text)
    });
    if account["sourceSlot"].as_u64() != Some(slot)
        || account["presence"] != "present"
        || account["role"] != "sysvar"
        || account["owner"] != SYSVAR_OWNER
        || account["executable"] != false
        || !valid_lamports
        || account["rentEpoch"] != u64::MAX.to_string()
        || account_data(account).is_err()
    {
        return Err(unsupported(
            "UNSUPPORTED_BANK_INPUT",
            "RECONSTRUCTION",
            format!("unproven override sysvar baseline:{}", account["pubkey"]),
        ));
    }
    Ok(())
}

pub fn hydrate_override_sysvar_baselines(
    overrides: &[RequestedAccountOverride],
    accounts: &[Value],
    context: &OverrideSysvarContext<'_>,
    history: &mut History<'_>,
) -> Result<OverrideSysvarBaselines> {
    if history.target_slot != context.target_slot {
        return Err(Error::new(
            "SOURCE_CONTEXT_MISMATCH",
            "override sysvar History target differs",
        ));
    }
    hydrate_override_sysvar_baselines_with_accounts(overrides, accounts, context, |key, slot| {
        history.accounts(&[key.to_owned()], slot, &Roles::default())
    })
}
